/* Config.c generated by valac 0.28.0, the Vala compiler
 * generated from Config.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




#define SUBMARINE_CONSTANTS_DATADIR "/usr/share"
#define SUBMARINE_CONSTANTS_PKGDATADIR "/usr/share/submarine"
#define SUBMARINE_CONSTANTS_GETTEXT_PACKAGE "submarine"
#define SUBMARINE_CONSTANTS_RELEASE_NAME "submarine"
#define SUBMARINE_CONSTANTS_VERSION "1.0.0"



