/* subtitle.c generated by valac 0.28.0, the Vala compiler
 * generated from subtitle.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>
#include <float.h>
#include <math.h>
#include <gobject/gvaluecollector.h>


#define SUBMARINE_TYPE_SUBTITLE (submarine_subtitle_get_type ())
#define SUBMARINE_SUBTITLE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), SUBMARINE_TYPE_SUBTITLE, SubmarineSubtitle))
#define SUBMARINE_SUBTITLE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), SUBMARINE_TYPE_SUBTITLE, SubmarineSubtitleClass))
#define SUBMARINE_IS_SUBTITLE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), SUBMARINE_TYPE_SUBTITLE))
#define SUBMARINE_IS_SUBTITLE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), SUBMARINE_TYPE_SUBTITLE))
#define SUBMARINE_SUBTITLE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), SUBMARINE_TYPE_SUBTITLE, SubmarineSubtitleClass))

typedef struct _SubmarineSubtitle SubmarineSubtitle;
typedef struct _SubmarineSubtitleClass SubmarineSubtitleClass;
typedef struct _SubmarineSubtitlePrivate SubmarineSubtitlePrivate;

#define SUBMARINE_TYPE_SERVER_INFO (submarine_server_info_get_type ())
typedef struct _SubmarineServerInfo SubmarineServerInfo;
#define _g_free0(var) (var = (g_free (var), NULL))
typedef struct _SubmarineParamSpecSubtitle SubmarineParamSpecSubtitle;

struct _SubmarineSubtitle {
	GTypeInstance parent_instance;
	volatile int ref_count;
	SubmarineSubtitlePrivate * priv;
};

struct _SubmarineSubtitleClass {
	GTypeClass parent_class;
	void (*finalize) (SubmarineSubtitle *self);
};

struct _SubmarineServerInfo {
	gchar* _name;
	gchar* _address;
	gchar* _code;
};

struct _SubmarineSubtitlePrivate {
	gchar* _format;
	gchar* _language;
	gdouble _rating;
	gchar* _data;
	SubmarineServerInfo _server_info;
	GValue _server_data;
};

struct _SubmarineParamSpecSubtitle {
	GParamSpec parent_instance;
};


static gpointer submarine_subtitle_parent_class = NULL;

gpointer submarine_subtitle_ref (gpointer instance);
void submarine_subtitle_unref (gpointer instance);
GParamSpec* submarine_param_spec_subtitle (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void submarine_value_set_subtitle (GValue* value, gpointer v_object);
void submarine_value_take_subtitle (GValue* value, gpointer v_object);
gpointer submarine_value_get_subtitle (const GValue* value);
GType submarine_subtitle_get_type (void) G_GNUC_CONST;
GType submarine_server_info_get_type (void) G_GNUC_CONST;
SubmarineServerInfo* submarine_server_info_dup (const SubmarineServerInfo* self);
void submarine_server_info_free (SubmarineServerInfo* self);
void submarine_server_info_copy (const SubmarineServerInfo* self, SubmarineServerInfo* dest);
void submarine_server_info_destroy (SubmarineServerInfo* self);
#define SUBMARINE_SUBTITLE_GET_PRIVATE(o) (G_TYPE_INSTANCE_GET_PRIVATE ((o), SUBMARINE_TYPE_SUBTITLE, SubmarineSubtitlePrivate))
enum  {
	SUBMARINE_SUBTITLE_DUMMY_PROPERTY
};
SubmarineSubtitle* submarine_subtitle_new (SubmarineServerInfo* server_info, GValue* server_data);
SubmarineSubtitle* submarine_subtitle_construct (GType object_type, SubmarineServerInfo* server_info, GValue* server_data);
static void submarine_subtitle_set_server_info (SubmarineSubtitle* self, SubmarineServerInfo* value);
static void submarine_subtitle_set_server_data (SubmarineSubtitle* self, GValue* value);
gchar* submarine_subtitle_get_filename (SubmarineSubtitle* self, const gchar* movie_filename);
const gchar* submarine_subtitle_get_format (SubmarineSubtitle* self);
void submarine_subtitle_set_format (SubmarineSubtitle* self, const gchar* value);
const gchar* submarine_subtitle_get_language (SubmarineSubtitle* self);
void submarine_subtitle_set_language (SubmarineSubtitle* self, const gchar* value);
gdouble submarine_subtitle_get_rating (SubmarineSubtitle* self);
void submarine_subtitle_set_rating (SubmarineSubtitle* self, gdouble value);
const gchar* submarine_subtitle_get_data (SubmarineSubtitle* self);
void submarine_subtitle_set_data (SubmarineSubtitle* self, const gchar* value);
void submarine_subtitle_get_server_info (SubmarineSubtitle* self, SubmarineServerInfo* result);
void submarine_subtitle_get_server_data (SubmarineSubtitle* self, GValue* result);
gboolean submarine_subtitle_get_has_data (SubmarineSubtitle* self);
static void submarine_subtitle_finalize (SubmarineSubtitle* obj);


SubmarineSubtitle* submarine_subtitle_construct (GType object_type, SubmarineServerInfo* server_info, GValue* server_data) {
	SubmarineSubtitle* self = NULL;
	SubmarineServerInfo _tmp0_ = {0};
	GValue _tmp1_ = {0};
	g_return_val_if_fail (server_info != NULL, NULL);
	g_return_val_if_fail (server_data != NULL, NULL);
	self = (SubmarineSubtitle*) g_type_create_instance (object_type);
	_tmp0_ = *server_info;
	submarine_subtitle_set_server_info (self, &_tmp0_);
	_tmp1_ = *server_data;
	submarine_subtitle_set_server_data (self, &_tmp1_);
	return self;
}


SubmarineSubtitle* submarine_subtitle_new (SubmarineServerInfo* server_info, GValue* server_data) {
	return submarine_subtitle_construct (SUBMARINE_TYPE_SUBTITLE, server_info, server_data);
}


static gchar* string_slice (const gchar* self, glong start, glong end) {
	gchar* result = NULL;
	glong string_length = 0L;
	gint _tmp0_ = 0;
	gint _tmp1_ = 0;
	glong _tmp2_ = 0L;
	glong _tmp5_ = 0L;
	gboolean _tmp8_ = FALSE;
	glong _tmp9_ = 0L;
	gboolean _tmp12_ = FALSE;
	glong _tmp13_ = 0L;
	glong _tmp16_ = 0L;
	glong _tmp17_ = 0L;
	glong _tmp18_ = 0L;
	glong _tmp19_ = 0L;
	glong _tmp20_ = 0L;
	gchar* _tmp21_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = strlen (self);
	_tmp1_ = _tmp0_;
	string_length = (glong) _tmp1_;
	_tmp2_ = start;
	if (_tmp2_ < ((glong) 0)) {
		glong _tmp3_ = 0L;
		glong _tmp4_ = 0L;
		_tmp3_ = string_length;
		_tmp4_ = start;
		start = _tmp3_ + _tmp4_;
	}
	_tmp5_ = end;
	if (_tmp5_ < ((glong) 0)) {
		glong _tmp6_ = 0L;
		glong _tmp7_ = 0L;
		_tmp6_ = string_length;
		_tmp7_ = end;
		end = _tmp6_ + _tmp7_;
	}
	_tmp9_ = start;
	if (_tmp9_ >= ((glong) 0)) {
		glong _tmp10_ = 0L;
		glong _tmp11_ = 0L;
		_tmp10_ = start;
		_tmp11_ = string_length;
		_tmp8_ = _tmp10_ <= _tmp11_;
	} else {
		_tmp8_ = FALSE;
	}
	g_return_val_if_fail (_tmp8_, NULL);
	_tmp13_ = end;
	if (_tmp13_ >= ((glong) 0)) {
		glong _tmp14_ = 0L;
		glong _tmp15_ = 0L;
		_tmp14_ = end;
		_tmp15_ = string_length;
		_tmp12_ = _tmp14_ <= _tmp15_;
	} else {
		_tmp12_ = FALSE;
	}
	g_return_val_if_fail (_tmp12_, NULL);
	_tmp16_ = start;
	_tmp17_ = end;
	g_return_val_if_fail (_tmp16_ <= _tmp17_, NULL);
	_tmp18_ = start;
	_tmp19_ = end;
	_tmp20_ = start;
	_tmp21_ = g_strndup (((gchar*) self) + _tmp18_, (gsize) (_tmp19_ - _tmp20_));
	result = _tmp21_;
	return result;
}


static gint string_last_index_of (const gchar* self, const gchar* needle, gint start_index) {
	gint result = 0;
	gchar* _result_ = NULL;
	gint _tmp0_ = 0;
	const gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	gchar* _tmp3_ = NULL;
	g_return_val_if_fail (self != NULL, 0);
	g_return_val_if_fail (needle != NULL, 0);
	_tmp0_ = start_index;
	_tmp1_ = needle;
	_tmp2_ = g_strrstr (((gchar*) self) + _tmp0_, (gchar*) _tmp1_);
	_result_ = _tmp2_;
	_tmp3_ = _result_;
	if (_tmp3_ != NULL) {
		gchar* _tmp4_ = NULL;
		_tmp4_ = _result_;
		result = (gint) (_tmp4_ - ((gchar*) self));
		return result;
	} else {
		result = -1;
		return result;
	}
}


gchar* submarine_subtitle_get_filename (SubmarineSubtitle* self, const gchar* movie_filename) {
	gchar* result = NULL;
	gchar* sub_filename = NULL;
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	const gchar* _tmp2_ = NULL;
	const gchar* _tmp3_ = NULL;
	gint _tmp4_ = 0;
	gchar* _tmp5_ = NULL;
	gchar* _tmp6_ = NULL;
	const gchar* _tmp7_ = NULL;
	gchar* _tmp8_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	g_return_val_if_fail (movie_filename != NULL, NULL);
	_tmp0_ = movie_filename;
	_tmp1_ = g_strdup (_tmp0_);
	sub_filename = _tmp1_;
	_tmp2_ = sub_filename;
	_tmp3_ = sub_filename;
	_tmp4_ = string_last_index_of (_tmp3_, ".", 0);
	_tmp5_ = string_slice (_tmp2_, (glong) 0, (glong) (_tmp4_ + 1));
	_tmp6_ = _tmp5_;
	_tmp7_ = self->priv->_format;
	_tmp8_ = g_strconcat (_tmp6_, _tmp7_, NULL);
	_g_free0 (sub_filename);
	sub_filename = _tmp8_;
	_g_free0 (_tmp6_);
	result = sub_filename;
	return result;
}


const gchar* submarine_subtitle_get_format (SubmarineSubtitle* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_format;
	result = _tmp0_;
	return result;
}


void submarine_subtitle_set_format (SubmarineSubtitle* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_format);
	self->priv->_format = _tmp1_;
}


const gchar* submarine_subtitle_get_language (SubmarineSubtitle* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_language;
	result = _tmp0_;
	return result;
}


void submarine_subtitle_set_language (SubmarineSubtitle* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_language);
	self->priv->_language = _tmp1_;
}


gdouble submarine_subtitle_get_rating (SubmarineSubtitle* self) {
	gdouble result;
	gdouble _tmp0_ = 0.0;
	g_return_val_if_fail (self != NULL, 0.0);
	_tmp0_ = self->priv->_rating;
	result = _tmp0_;
	return result;
}


void submarine_subtitle_set_rating (SubmarineSubtitle* self, gdouble value) {
	gdouble _tmp0_ = 0.0;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	self->priv->_rating = _tmp0_;
}


const gchar* submarine_subtitle_get_data (SubmarineSubtitle* self) {
	const gchar* result;
	const gchar* _tmp0_ = NULL;
	g_return_val_if_fail (self != NULL, NULL);
	_tmp0_ = self->priv->_data;
	result = _tmp0_;
	return result;
}


void submarine_subtitle_set_data (SubmarineSubtitle* self, const gchar* value) {
	const gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	g_return_if_fail (self != NULL);
	_tmp0_ = value;
	_tmp1_ = g_strdup (_tmp0_);
	_g_free0 (self->priv->_data);
	self->priv->_data = _tmp1_;
}


void submarine_subtitle_get_server_info (SubmarineSubtitle* self, SubmarineServerInfo* result) {
	SubmarineServerInfo _tmp0_ = {0};
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_server_info;
	*result = _tmp0_;
	return;
}


static void submarine_subtitle_set_server_info (SubmarineSubtitle* self, SubmarineServerInfo* value) {
	SubmarineServerInfo _tmp0_ = {0};
	SubmarineServerInfo _tmp1_ = {0};
	g_return_if_fail (self != NULL);
	_tmp0_ = *value;
	submarine_server_info_copy (&_tmp0_, &_tmp1_);
	submarine_server_info_destroy (&self->priv->_server_info);
	self->priv->_server_info = _tmp1_;
}


void submarine_subtitle_get_server_data (SubmarineSubtitle* self, GValue* result) {
	GValue _tmp0_ = {0};
	g_return_if_fail (self != NULL);
	_tmp0_ = self->priv->_server_data;
	*result = _tmp0_;
	return;
}


static void submarine_subtitle_set_server_data (SubmarineSubtitle* self, GValue* value) {
	GValue _tmp0_ = {0};
	GValue _tmp1_ = {0};
	g_return_if_fail (self != NULL);
	_tmp0_ = *value;
	if (G_IS_VALUE (&_tmp0_)) {
		g_value_init (&_tmp1_, G_VALUE_TYPE (&_tmp0_));
		g_value_copy (&_tmp0_, &_tmp1_);
	} else {
		_tmp1_ = _tmp0_;
	}
	G_IS_VALUE (&self->priv->_server_data) ? (g_value_unset (&self->priv->_server_data), NULL) : NULL;
	self->priv->_server_data = _tmp1_;
}


gboolean submarine_subtitle_get_has_data (SubmarineSubtitle* self) {
	gboolean result;
	const gchar* _tmp0_ = NULL;
	gint _tmp1_ = 0;
	gint _tmp2_ = 0;
	g_return_val_if_fail (self != NULL, FALSE);
	_tmp0_ = self->priv->_data;
	_tmp1_ = strlen (_tmp0_);
	_tmp2_ = _tmp1_;
	result = _tmp2_ > 0;
	return result;
}


static void submarine_value_subtitle_init (GValue* value) {
	value->data[0].v_pointer = NULL;
}


static void submarine_value_subtitle_free_value (GValue* value) {
	if (value->data[0].v_pointer) {
		submarine_subtitle_unref (value->data[0].v_pointer);
	}
}


static void submarine_value_subtitle_copy_value (const GValue* src_value, GValue* dest_value) {
	if (src_value->data[0].v_pointer) {
		dest_value->data[0].v_pointer = submarine_subtitle_ref (src_value->data[0].v_pointer);
	} else {
		dest_value->data[0].v_pointer = NULL;
	}
}


static gpointer submarine_value_subtitle_peek_pointer (const GValue* value) {
	return value->data[0].v_pointer;
}


static gchar* submarine_value_subtitle_collect_value (GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	if (collect_values[0].v_pointer) {
		SubmarineSubtitle* object;
		object = collect_values[0].v_pointer;
		if (object->parent_instance.g_class == NULL) {
			return g_strconcat ("invalid unclassed object pointer for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		} else if (!g_value_type_compatible (G_TYPE_FROM_INSTANCE (object), G_VALUE_TYPE (value))) {
			return g_strconcat ("invalid object type `", g_type_name (G_TYPE_FROM_INSTANCE (object)), "' for value type `", G_VALUE_TYPE_NAME (value), "'", NULL);
		}
		value->data[0].v_pointer = submarine_subtitle_ref (object);
	} else {
		value->data[0].v_pointer = NULL;
	}
	return NULL;
}


static gchar* submarine_value_subtitle_lcopy_value (const GValue* value, guint n_collect_values, GTypeCValue* collect_values, guint collect_flags) {
	SubmarineSubtitle** object_p;
	object_p = collect_values[0].v_pointer;
	if (!object_p) {
		return g_strdup_printf ("value location for `%s' passed as NULL", G_VALUE_TYPE_NAME (value));
	}
	if (!value->data[0].v_pointer) {
		*object_p = NULL;
	} else if (collect_flags & G_VALUE_NOCOPY_CONTENTS) {
		*object_p = value->data[0].v_pointer;
	} else {
		*object_p = submarine_subtitle_ref (value->data[0].v_pointer);
	}
	return NULL;
}


GParamSpec* submarine_param_spec_subtitle (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags) {
	SubmarineParamSpecSubtitle* spec;
	g_return_val_if_fail (g_type_is_a (object_type, SUBMARINE_TYPE_SUBTITLE), NULL);
	spec = g_param_spec_internal (G_TYPE_PARAM_OBJECT, name, nick, blurb, flags);
	G_PARAM_SPEC (spec)->value_type = object_type;
	return G_PARAM_SPEC (spec);
}


gpointer submarine_value_get_subtitle (const GValue* value) {
	g_return_val_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SUBMARINE_TYPE_SUBTITLE), NULL);
	return value->data[0].v_pointer;
}


void submarine_value_set_subtitle (GValue* value, gpointer v_object) {
	SubmarineSubtitle* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SUBMARINE_TYPE_SUBTITLE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, SUBMARINE_TYPE_SUBTITLE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
		submarine_subtitle_ref (value->data[0].v_pointer);
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		submarine_subtitle_unref (old);
	}
}


void submarine_value_take_subtitle (GValue* value, gpointer v_object) {
	SubmarineSubtitle* old;
	g_return_if_fail (G_TYPE_CHECK_VALUE_TYPE (value, SUBMARINE_TYPE_SUBTITLE));
	old = value->data[0].v_pointer;
	if (v_object) {
		g_return_if_fail (G_TYPE_CHECK_INSTANCE_TYPE (v_object, SUBMARINE_TYPE_SUBTITLE));
		g_return_if_fail (g_value_type_compatible (G_TYPE_FROM_INSTANCE (v_object), G_VALUE_TYPE (value)));
		value->data[0].v_pointer = v_object;
	} else {
		value->data[0].v_pointer = NULL;
	}
	if (old) {
		submarine_subtitle_unref (old);
	}
}


static void submarine_subtitle_class_init (SubmarineSubtitleClass * klass) {
	submarine_subtitle_parent_class = g_type_class_peek_parent (klass);
	((SubmarineSubtitleClass *) klass)->finalize = submarine_subtitle_finalize;
	g_type_class_add_private (klass, sizeof (SubmarineSubtitlePrivate));
}


static void submarine_subtitle_instance_init (SubmarineSubtitle * self) {
	gchar* _tmp0_ = NULL;
	gchar* _tmp1_ = NULL;
	gchar* _tmp2_ = NULL;
	self->priv = SUBMARINE_SUBTITLE_GET_PRIVATE (self);
	_tmp0_ = g_strdup ("");
	self->priv->_format = _tmp0_;
	_tmp1_ = g_strdup ("");
	self->priv->_language = _tmp1_;
	self->priv->_rating = 0.0;
	_tmp2_ = g_strdup ("");
	self->priv->_data = _tmp2_;
	self->ref_count = 1;
}


static void submarine_subtitle_finalize (SubmarineSubtitle* obj) {
	SubmarineSubtitle * self;
	self = G_TYPE_CHECK_INSTANCE_CAST (obj, SUBMARINE_TYPE_SUBTITLE, SubmarineSubtitle);
	g_signal_handlers_destroy (self);
	_g_free0 (self->priv->_format);
	_g_free0 (self->priv->_language);
	_g_free0 (self->priv->_data);
	submarine_server_info_destroy (&self->priv->_server_info);
	G_IS_VALUE (&self->priv->_server_data) ? (g_value_unset (&self->priv->_server_data), NULL) : NULL;
}


GType submarine_subtitle_get_type (void) {
	static volatile gsize submarine_subtitle_type_id__volatile = 0;
	if (g_once_init_enter (&submarine_subtitle_type_id__volatile)) {
		static const GTypeValueTable g_define_type_value_table = { submarine_value_subtitle_init, submarine_value_subtitle_free_value, submarine_value_subtitle_copy_value, submarine_value_subtitle_peek_pointer, "p", submarine_value_subtitle_collect_value, "p", submarine_value_subtitle_lcopy_value };
		static const GTypeInfo g_define_type_info = { sizeof (SubmarineSubtitleClass), (GBaseInitFunc) NULL, (GBaseFinalizeFunc) NULL, (GClassInitFunc) submarine_subtitle_class_init, (GClassFinalizeFunc) NULL, NULL, sizeof (SubmarineSubtitle), 0, (GInstanceInitFunc) submarine_subtitle_instance_init, &g_define_type_value_table };
		static const GTypeFundamentalInfo g_define_type_fundamental_info = { (G_TYPE_FLAG_CLASSED | G_TYPE_FLAG_INSTANTIATABLE | G_TYPE_FLAG_DERIVABLE | G_TYPE_FLAG_DEEP_DERIVABLE) };
		GType submarine_subtitle_type_id;
		submarine_subtitle_type_id = g_type_register_fundamental (g_type_fundamental_next (), "SubmarineSubtitle", &g_define_type_info, &g_define_type_fundamental_info, 0);
		g_once_init_leave (&submarine_subtitle_type_id__volatile, submarine_subtitle_type_id);
	}
	return submarine_subtitle_type_id__volatile;
}


gpointer submarine_subtitle_ref (gpointer instance) {
	SubmarineSubtitle* self;
	self = instance;
	g_atomic_int_inc (&self->ref_count);
	return instance;
}


void submarine_subtitle_unref (gpointer instance) {
	SubmarineSubtitle* self;
	self = instance;
	if (g_atomic_int_dec_and_test (&self->ref_count)) {
		SUBMARINE_SUBTITLE_GET_CLASS (self)->finalize (self);
		g_type_free_instance ((GTypeInstance *) self);
	}
}



