/* Config.c generated by valac 0.28.0, the Vala compiler
 * generated from Config.vala, do not modify */


#include <glib.h>
#include <glib-object.h>
#include <stdlib.h>
#include <string.h>




#define CONSTANTS_DATADIR "/usr/share"
#define CONSTANTS_PKGDATADIR "/usr/share/submarine"
#define CONSTANTS_GETTEXT_PACKAGE "submarine"
#define CONSTANTS_RELEASE_NAME "submarine"
#define CONSTANTS_VERSION "0.1.6"



